site_name: Booster Bot Docs
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.follow
  logo: "images/bb.png"
  custom_dir: docs/overrides
  favicon: "images/favicon.ico"
  language: en
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      accent: "orange"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      accent: "yellow"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home:
    - index.md
    # - Table of contents: summary.md
    - Basic bot setup: setupguide.md
    # - FAQs: faq.md
  - Setup Commands:
    - Setup: ./commands/setup.md
    - Greet: ./commands/greet.md
    - Rank: ./commands/rank.md
    - Emoji: ./commands/emoji.md
    - Stats: ./commands/stats.md
    - Vars (Variables): ./commands/variables.md
  - Booster Commands:
    - Custom Roles: ./commands/role.md
    - Gifting Roles: ./commands/gift.md
    - Level Roles: ./commands/lvlrole.md
    - Auto Reaction: ./commands/reaction.md
    - Boost Level Roles: ./commands/lvlrole.md
    - Age Roles: ./commands/agerole.md
  - User Commands:
    - Guide: ./commands/guide.md
    - Count: ./commands/count.md
    - Invite: ./commands/invite.md
    - Voters: ./commands/voters.md
    - User Info: ./commands/userinfo.md
    - Reminders: ./commands/reminder.md

extra:
  social:
    - icon: "fontawesome/solid/globe"
      link: "https://boosterbot.xyz/"
      name: BoosterBot website
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/DiabolusGX/mkdocs-boosterbot"
      name: Github repository
    - icon: "fontawesome/brands/discord"
      link: "https://boosterbot.xyz/support"
      name: Support Server
  # generator: false # to remove MkDocs footer

repo_name: "boosterbot-docs"
repo_url: "https://github.com/DiabolusGX/mkdocs-boosterbot"

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - md_in_html
  - attr_list
  - footnotes
  - meta
  - def_list

extra_css:
  - overrides/stylesheets/extra.css

plugins:
  - search:
      separator: '[\s\-\.\_]'

copyright: "Copyright &copy; 2021-2022 Dev Studios"
