site_name: Booster Bot Docs
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.follow
  logo: "images/bb.png"
  custom_dir: docs/overrides
  favicon: "images/favicon.ico"
  language: en
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      accent: "orange"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      accent: "yellow"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home:
    - index.md
    - Basic bot setup: setup.md
    - FAQs: faq.md
  - Setup Commands:
    - Setup: ./commands/admin/setup.md
    - Greet: ./commands/admin/greet.md
    - Rank: ./commands/admin/rank.md
    - Emoji: ./commands/admin/emoji.md
    - Stats: ./commands/admin/stats.md
    - Private roles: ./commands/admin/privateRoleSetup.md
    - Private channels: ./commands/admin/privateChannelSetup.md
    - Vars (Variables): ./commands/admin/variables.md
  - Booster Commands:
    - Custom Roles: ./commands/boosters/role.md
    - Gifting Roles: ./commands/boosters/gift.md
    - Level Roles: ./commands/boosters/lvlrole.md
    - Auto Reaction: ./commands/boosters/reaction.md
    - Age Roles: ./commands/boosters/agerole.md
    - Role List: ./commands/boosters/rolelist.md
    - Private channels: ./commands/boosters/privateChannel.md
  - User Commands:
    - Guide: ./commands/users/guide.md
    - Count: ./commands/users/count.md
    - Invite: ./commands/users/invite.md
    - Voters: ./commands/users/voters.md
    - Premium: ./commands/users/premium.md
    - User Info: ./commands/users/userinfo.md
    - Reminders: ./commands/users/reminder.md

extra:
  social:
    - icon: "fontawesome/solid/globe"
      link: "https://boosterbot.xyz/"
      name: BoosterBot website
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/Booster-Bot-Discord/mkdocs-boosterbot"
      name: Github repository
    - icon: "fontawesome/brands/discord"
      link: "https://boosterbot.xyz/support"
      name: Support Server
  # generator: false # to remove MkDocs footer

repo_name: "boosterbot-docs"
repo_url: "https://github.com/Booster-Bot-Discord/mkdocs-boosterbot"

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - md_in_html
  - attr_list
  - footnotes
  - meta
  - def_list

extra_css:
  - overrides/stylesheets/extra.css

plugins:
  - search:
      separator: '[\s\-\.\_]'

copyright: "Copyright &copy; 2021-2022 Dev Studios"
